# raise Exception("何らかの例外")

try:
    raise Exception("何らかの例外")
except Exception as E:
    print(E)
